In [1]:
import os
import numpy as np
import scipy as sci

zadania = "zadania"

In [2]:
print("########## Zadanie 3 ##########")

A = np.loadtxt(os.path.join(zadania, "zad3.txt"), float, delimiter=" ", ndmin=2)
b = np.loadtxt(os.path.join(zadania, "zad3_b.txt"), float, delimiter=" ", ndmin=2)

print(A)
print(b)

x, _, _, _ = sci.linalg.lstsq(A, b)
print(x)

########## Zadanie 3 ##########
[[0.000e+00 0.000e+00 1.000e+00]
 [6.250e+04 2.500e+02 1.000e+00]
 [2.500e+05 5.000e+02 1.000e+00]
 [5.625e+05 7.500e+02 1.000e+00]
 [1.000e+06 1.000e+03 1.000e+00]]
[[ 0.]
 [ 8.]
 [15.]
 [19.]
 [20.]]
[[-1.94285714e-05]
 [ 3.98285714e-02]
 [-2.28571429e-01]]
