In [10]:
import os
import scipy as sci
import numpy as np

zadania = "zadania"

Least square method

In [11]:
print("########## Zadanie 4 A ##########")

A = np.loadtxt(os.path.join(zadania, "zad4A.txt"), float, delimiter=" ", ndmin=2)
b = np.loadtxt(os.path.join(zadania, "zad4_b.txt"), float, delimiter=" ", ndmin=2)

x, _, _, _ = sci.linalg.lstsq(A, b)
print("A = \n", A)
print("b = \n", b)
print("x = \n", x)

########## Zadanie 4 A ##########
A = 
 [[ 1. -5.]
 [ 1. -4.]
 [ 1. -3.]
 [ 1. -2.]
 [ 1. -1.]
 [ 1.  0.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]]
b = 
 [[ 2.]
 [ 7.]
 [ 9.]
 [12.]
 [13.]
 [14.]
 [14.]
 [13.]
 [10.]
 [ 8.]
 [ 4.]]
x = 
 [[9.63636364]
 [0.18181818]]


Run the comparison to original values for function
$$ f(x) = a_0 + a_1 * x$$

In [12]:
samplesLen = len(b)
coefsNum = len(x)
y = []
for i in range(samplesLen):
    y.append(A[i][0]*x[0] + A[i][1]*x[1])
    print("f(", A[i][1] , ") = ", b[i], " vs ", y[i])

f( -5.0 ) =  [2.]  vs  [8.72727273]
f( -4.0 ) =  [7.]  vs  [8.90909091]
f( -3.0 ) =  [9.]  vs  [9.09090909]
f( -2.0 ) =  [12.]  vs  [9.27272727]
f( -1.0 ) =  [13.]  vs  [9.45454545]
f( 0.0 ) =  [14.]  vs  [9.63636364]
f( 1.0 ) =  [14.]  vs  [9.81818182]
f( 2.0 ) =  [13.]  vs  [10.]
f( 3.0 ) =  [10.]  vs  [10.18181818]
f( 4.0 ) =  [8.]  vs  [10.36363636]
f( 5.0 ) =  [4.]  vs  [10.54545455]
