In [6]:
import os
import scipy as sci
import numpy as np

zadania = "zadania"

Least square method

In [7]:
print("########## Zadanie 4 A ##########")

A = np.loadtxt(os.path.join(zadania, "zad4A.txt"), float, delimiter=" ", ndmin=2)
b = np.loadtxt(os.path.join(zadania, "zad4_b.txt"), float, delimiter=" ", ndmin=2)

x, _, _, _ = sci.linalg.lstsq(A, b)
print("A^T = \n", A.T)
print("b^T = \n", b.T)
print("x^T = \n", x.T)

########## Zadanie 4 A ##########
A^T = 
 [[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [-5. -4. -3. -2. -1.  0.  1.  2.  3.  4.  5.]]
b^T = 
 [[ 2.  7.  9. 12. 13. 14. 14. 13. 10.  8.  4.]]
x^T = 
 [[9.63636364 0.18181818]]


Run the comparison to original values for function
$$ f(x) = a_0 + a_1 * x$$

In [8]:
samplesLen = len(b)
coefsNum = len(x)
y = []
for i in range(samplesLen):
    y.append(A[i][0]*x[0] + A[i][1]*x[1])
    print("f(", A[i][1] , ") = ", b[i], " vs ", y[i])

f( -5.0 ) =  [2.]  vs  [8.72727273]
f( -4.0 ) =  [7.]  vs  [8.90909091]
f( -3.0 ) =  [9.]  vs  [9.09090909]
f( -2.0 ) =  [12.]  vs  [9.27272727]
f( -1.0 ) =  [13.]  vs  [9.45454545]
f( 0.0 ) =  [14.]  vs  [9.63636364]
f( 1.0 ) =  [14.]  vs  [9.81818182]
f( 2.0 ) =  [13.]  vs  [10.]
f( 3.0 ) =  [10.]  vs  [10.18181818]
f( 4.0 ) =  [8.]  vs  [10.36363636]
f( 5.0 ) =  [4.]  vs  [10.54545455]


In [9]:
print("########## Zadanie 4 B ##########")

A = np.loadtxt(os.path.join(zadania, "zad4B.txt"), float, delimiter=" ", ndmin=2)
b = np.loadtxt(os.path.join(zadania, "zad4_b.txt"), float, delimiter=" ", ndmin=2)

x, _, _, _ = sci.linalg.lstsq(A, b)
print("A^T = \n", A.T)
print("b^T = \n", b.T)
print("x^T = \n", x.T)

########## Zadanie 4 B ##########
A^T = 
 [[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [-5. -4. -3. -2. -1.  0.  1.  2.  3.  4.  5.]
 [25. 16.  9.  4.  1.  0.  1.  4.  9. 16. 25.]]
b^T = 
 [[ 2.  7.  9. 12. 13. 14. 14. 13. 10.  8.  4.]]
x^T = 
 [[13.97202797  0.18181818 -0.43356643]]


In [10]:
samplesLen = len(b)
coefsNum = len(x)
y = []
for i in range(samplesLen):
    y.append(A[i][0]*x[0] + A[i][1]*x[1] + A[i][2]*x[2])
    print("f(", A[i][1] , ") = ", b[i], " vs ", y[i])

f( -5.0 ) =  [2.]  vs  [2.22377622]
f( -4.0 ) =  [7.]  vs  [6.30769231]
f( -3.0 ) =  [9.]  vs  [9.52447552]
f( -2.0 ) =  [12.]  vs  [11.87412587]
f( -1.0 ) =  [13.]  vs  [13.35664336]
f( 0.0 ) =  [14.]  vs  [13.97202797]
f( 1.0 ) =  [14.]  vs  [13.72027972]
f( 2.0 ) =  [13.]  vs  [12.6013986]
f( 3.0 ) =  [10.]  vs  [10.61538462]
f( 4.0 ) =  [8.]  vs  [7.76223776]
f( 5.0 ) =  [4.]  vs  [4.04195804]
